title: Bundle
description: Effortless page specific JavaScript modules in Laravel/Livewire apps
remote_theme: just-the-docs/just-the-docs
color_scheme: light
# color_scheme: dark
logo: "/assets/logo.svg"

url: https://laravel-bundle.dev

aux_links: # remove if you don't want this link to appear on your pages
  Github: https://github.com/gwleuverink/bundle

enable_copy_code_button: true

search_enabled: true
search.heading_level: 3
search.previews: 5
search.button: true

callouts:
  note:
    title: note
    color: purple
  warning:
    title: warning
    color: red
