title: Bundle
description: Effortless page specific JavaScript modules in Laravel/Livewire apps
remote_theme: just-the-docs/just-the-docs
logo: "/assets/logo.svg"
color_scheme: dark

ga_tracking: G-HRG2CG9KZ7
ga_tracking_anonymize_ip: true

url: https://laravel-bundle.dev

aux_links_new_tab: true
aux_links:
  GitHub: https://github.com/gwleuverink/bundle

enable_copy_code_button: true

search_enabled: true
search.heading_level: 3
search.previews: 5
search.button: true

callouts:
  note:
    title: note
    color: purple
  warning:
    title: warning
    color: red
