name: tests

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:
  skip-duplicates:
    continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest

    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}

    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          cancel_others: "true"
          concurrent_skipping: "same_content"
          skip_after_successful_duplicate: "true"
          paths_ignore: '["**/README.md", "**/docs/**"]'

  workbench-tests:
    needs: skip-duplicates
    if: needs.skip-duplicates.outputs.should_skip != 'true'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: zip
          coverage: xdebug

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install Composer dependecies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Directory Permissions
        run: sudo chown -R $(whoami) vendor/pestphp/pest/.temp vendor/orchestra

      - name: Install Bun & link Workbench directories
        run: composer setup-workbench

      - name: Run Unit & Feature tests
        run: composer test

    #   - name: Run Browser tests
    #     run: composer test-browser

    #   - name: Generate coverage report (threshold 90%)
    #     run: ./vendor/bin/pest --bail --retry --coverage --min=90 --coverage-clover clover.xml

    #   - name: Upload coverage reports to Codecov
    #     uses: codecov/codecov-action@v3
    #     env:
    #       CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
